services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5001
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - CORS_ORIGIN=http://localhost:8080
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://server:5001
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: unless-stopped